// <auto-generated />
using System;
using Aduasis.Api.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aduasis.Api.Datos.Migraciones
{
    [DbContext(typeof(ContextoAduasis))]
    [Migration("20260929200721_CrearTablasHistorialAsignaciones")]
    partial class CrearTablasHistorialAsignaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aduasis.Api.Modelos.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<string>("CodigoActivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_activo");

                    b.Property<string>("CodigoQr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_qr");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CreadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por_id");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("direccion_ip");

                    b.Property<int?>("EspacioId")
                        .HasColumnType("integer")
                        .HasColumnName("espacio_id");

                    b.Property<string>("Especificaciones")
                        .HasColumnType("text")
                        .HasColumnName("especificaciones");

                    b.Property<int>("EstadoActivoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_activo_id");

                    b.Property<DateOnly?>("FechaAdquisicion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_adquisicion");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<int?>("ModeloActivoId")
                        .HasColumnType("integer")
                        .HasColumnName("modelo_activo_id");

                    b.Property<string>("NombreDescriptivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_descriptivo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("TipoActivoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_activo_id");

                    b.Property<int?>("UsuarioAsignadoId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_asignado_id");

                    b.HasKey("Id");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("idx_activos_area");

                    b.HasIndex("CodigoActivo")
                        .IsUnique()
                        .HasDatabaseName("idx_activos_codigo_activo");

                    b.HasIndex("CodigoQr")
                        .IsUnique()
                        .HasDatabaseName("idx_activos_codigo_qr")
                        .HasFilter("codigo_qr IS NOT NULL");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("EspacioId")
                        .HasDatabaseName("idx_activos_espacio");

                    b.HasIndex("EstadoActivoId")
                        .HasDatabaseName("idx_activos_estado");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ModeloActivoId");

                    b.HasIndex("TipoActivoId");

                    b.HasIndex("UsuarioAsignadoId");

                    b.ToTable("activos", (string)null);
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("PisoId")
                        .HasColumnType("integer")
                        .HasColumnName("piso_id");

                    b.HasKey("Id");

                    b.HasIndex("PisoId", "Nombre")
                        .HasDatabaseName("idx_areas_piso_nombre");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Asignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivoId")
                        .HasColumnType("integer")
                        .HasColumnName("activo_id");

                    b.Property<int?>("ActivoId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int?>("RegistradoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("registrado_por_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId")
                        .HasDatabaseName("idx_asignaciones_activo_id");

                    b.HasIndex("ActivoId1");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ActivoId", "FechaFin")
                        .HasDatabaseName("idx_asignaciones_activo_activa");

                    b.ToTable("asignaciones", (string)null);
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Edificio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_edificios_nombre");

                    b.ToTable("edificios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Edificio principal",
                            Nombre = "Aduana Nacional - Gerencia Regional La Paz"
                        });
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Espacio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("PisoId")
                        .HasColumnType("integer")
                        .HasColumnName("piso_id");

                    b.HasKey("Id");

                    b.HasIndex("PisoId", "Nombre")
                        .HasDatabaseName("idx_espacios_piso_nombre");

                    b.ToTable("espacios", (string)null);
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.EstadoActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_estados_activo_nombre");

                    b.ToTable("estados_activo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "El activo funciona correctamente",
                            Nombre = "Operativo"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "El activo está siendo reparado",
                            Nombre = "En reparación"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "El activo está almacenado sin asignar",
                            Nombre = "En bodega"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "El activo fue retirado del servicio",
                            Nombre = "Dado de baja"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "El activo está prestado temporalmente",
                            Nombre = "En préstamo"
                        });
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.HistorialActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivoId")
                        .HasColumnType("integer")
                        .HasColumnName("activo_id");

                    b.Property<int?>("ActivoId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsNotaManual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_nota_manual");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_evento");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId")
                        .HasDatabaseName("idx_historial_activos_activo_id");

                    b.HasIndex("ActivoId1");

                    b.HasIndex("CreadoEn")
                        .HasDatabaseName("idx_historial_activos_creado_en");

                    b.HasIndex("UsuarioId");

                    b.ToTable("historial_activos", (string)null);
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_marcas_nombre");

                    b.ToTable("marcas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Dell"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "HP"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cisco"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Lenovo"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Epson"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Samsung"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Acer"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Asus"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "APC"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Huawei"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "TP-Link"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Otra"
                        });
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.ModeloActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_modelos_activo_marca_nombre");

                    b.ToTable("modelos_activo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MarcaId = 1,
                            Nombre = "OptiPlex 7070"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MarcaId = 1,
                            Nombre = "OptiPlex 3080"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MarcaId = 1,
                            Nombre = "Latitude 5420"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MarcaId = 2,
                            Nombre = "ProDesk 400 G7"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MarcaId = 2,
                            Nombre = "LaserJet Enterprise"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MarcaId = 2,
                            Nombre = "EliteBook 840"
                        });
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Piso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("EdificioId")
                        .HasColumnType("integer")
                        .HasColumnName("edificio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_pisos_edificio_nombre");

                    b.ToTable("pisos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EdificioId = 1,
                            Nombre = "Planta Baja",
                            Orden = 0
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EdificioId = 1,
                            Nombre = "Piso 1",
                            Orden = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EdificioId = 1,
                            Nombre = "Exterior",
                            Orden = 99
                        });
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_roles_nombre");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Acceso total al sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Gestión de activos y seguimiento de tickets",
                            Nombre = "Funcionario"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Acceso limitado a consultas y soporte básico",
                            Nombre = "Pasante"
                        });
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.TipoActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_tipos_activo_nombre");

                    b.ToTable("tipos_activo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Computadoras de escritorio, laptops y similares",
                            Nombre = "Equipo de computación"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Impresoras láser, de inyección y multifuncionales",
                            Nombre = "Impresora"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Switches de red administrables y no administrables",
                            Nombre = "Switch"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Routers y equipos de enrutamiento",
                            Nombre = "Router"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Sistemas de alimentación ininterrumpida",
                            Nombre = "UPS"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Monitores y pantallas",
                            Nombre = "Monitor"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Teléfonos y dispositivos de telefonía IP",
                            Nombre = "Teléfono IP"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Escáneres documentales y de código de barras",
                            Nombre = "Escáner"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Servidores físicos y de rack",
                            Nombre = "Servidor"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Otros equipos tecnológicos",
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.TokenRefresco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origen");

                    b.Property<bool>("Revocado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("revocado");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<bool>("Usado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("usado");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_tokens_refresco_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_tokens_refresco_usuario_id");

                    b.ToTable("tokens_refresco", (string)null);
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("idx_usuarios_correo");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("idx_usuarios_nombre_usuario");

                    b.HasIndex("RolId")
                        .HasDatabaseName("idx_usuarios_rol_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Activo", b =>
                {
                    b.HasOne("Aduasis.Api.Modelos.Area", "Area")
                        .WithMany("Activos")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aduasis.Api.Modelos.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aduasis.Api.Modelos.Espacio", "Espacio")
                        .WithMany("Activos")
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aduasis.Api.Modelos.EstadoActivo", "EstadoActivo")
                        .WithMany("Activos")
                        .HasForeignKey("EstadoActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aduasis.Api.Modelos.Marca", "Marca")
                        .WithMany("Activos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aduasis.Api.Modelos.ModeloActivo", "ModeloActivo")
                        .WithMany("Activos")
                        .HasForeignKey("ModeloActivoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Aduasis.Api.Modelos.TipoActivo", "TipoActivo")
                        .WithMany("Activos")
                        .HasForeignKey("TipoActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aduasis.Api.Modelos.Usuario", "UsuarioAsignado")
                        .WithMany()
                        .HasForeignKey("UsuarioAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");

                    b.Navigation("CreadoPor");

                    b.Navigation("Espacio");

                    b.Navigation("EstadoActivo");

                    b.Navigation("Marca");

                    b.Navigation("ModeloActivo");

                    b.Navigation("TipoActivo");

                    b.Navigation("UsuarioAsignado");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Area", b =>
                {
                    b.HasOne("Aduasis.Api.Modelos.Piso", "Piso")
                        .WithMany("Areas")
                        .HasForeignKey("PisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Piso");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Asignacion", b =>
                {
                    b.HasOne("Aduasis.Api.Modelos.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aduasis.Api.Modelos.Activo", null)
                        .WithMany("Asignaciones")
                        .HasForeignKey("ActivoId1");

                    b.HasOne("Aduasis.Api.Modelos.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aduasis.Api.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activo");

                    b.Navigation("RegistradoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Espacio", b =>
                {
                    b.HasOne("Aduasis.Api.Modelos.Piso", "Piso")
                        .WithMany("Espacios")
                        .HasForeignKey("PisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Piso");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.HistorialActivo", b =>
                {
                    b.HasOne("Aduasis.Api.Modelos.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aduasis.Api.Modelos.Activo", null)
                        .WithMany("Historial")
                        .HasForeignKey("ActivoId1");

                    b.HasOne("Aduasis.Api.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.ModeloActivo", b =>
                {
                    b.HasOne("Aduasis.Api.Modelos.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Piso", b =>
                {
                    b.HasOne("Aduasis.Api.Modelos.Edificio", "Edificio")
                        .WithMany("Pisos")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Edificio");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.TokenRefresco", b =>
                {
                    b.HasOne("Aduasis.Api.Modelos.Usuario", "Usuario")
                        .WithMany("TokensRefresco")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Usuario", b =>
                {
                    b.HasOne("Aduasis.Api.Modelos.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Activo", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Area", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Edificio", b =>
                {
                    b.Navigation("Pisos");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Espacio", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.EstadoActivo", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Marca", b =>
                {
                    b.Navigation("Activos");

                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.ModeloActivo", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Piso", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Espacios");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.TipoActivo", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("Aduasis.Api.Modelos.Usuario", b =>
                {
                    b.Navigation("TokensRefresco");
                });
#pragma warning restore 612, 618
        }
    }
}
